# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alibi.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61libi.proto\x12\x04grpc\"U\n\x12StudentFaceRequest\x12\x15\n\rdetected_name\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63uracy\x18\x02 \x01(\x02\x12\x16\n\x0eimage_data_b64\x18\x03 \x01(\t\"7\n\x13StudentFaceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2Z\n\x12ImageUploadService\x12\x44\n\x0bUploadImage\x12\x18.grpc.StudentFaceRequest\x1a\x19.grpc.StudentFaceResponse(\x01\x42\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alibi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_STUDENTFACEREQUEST']._serialized_start=21
  _globals['_STUDENTFACEREQUEST']._serialized_end=106
  _globals['_STUDENTFACERESPONSE']._serialized_start=108
  _globals['_STUDENTFACERESPONSE']._serialized_end=163
  _globals['_IMAGEUPLOADSERVICE']._serialized_start=165
  _globals['_IMAGEUPLOADSERVICE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
